#!/bin/sh

mkdir -p ~/.vim

./script/setup "vim"

# Install vundle
./script/info.sh "Downloading Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

./script/info.sh "Downloading vim plugins"
vim +PlugInstall +qa

# make links for neovim
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -sf ~/.vim/autoload $XDG_CONFIG_HOME/nvim/autoload
ln -sf ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim

