#!/bin/sh

mkdir ~/.config 2>/dev/null

./script/setup "zsh"

./script/info.sh "Downloading Antigen"
curl https://cdn.rawgit.com/zsh-users/antigen/v1.0.4/antigen.zsh > "$HOME/.antigen.zsh"

./script/info.sh "Downloading zsh-pure theme"
bin/git-clone-or-sync https://github.com/sindresorhus/pure ~/.config/pure

mkdir ~/.config/zfunctions 2>/dev/null

ln -s "$HOME/.config/pure/pure.zsh" "$HOME/.config/zfunctions/prompt_pure_setup" 2>/dev/null
ln -s "$HOME/.config/pure/async.zsh" "$HOME/.config/zfunctions/async" 2>/dev/null
exit 0
